### ISSUE TITLE
Is there a BOM for your project?

### ISSUE THREAD

**Issue by xoxota99** [jayflatland/HighFrequencyTwister#1]
What motors / motor drivers did you use? what cameras? Thanks!

**Comment by jayflatland** [comment]
Hi!  Not sure I wrote down BOM anywhere.

I've attached a screenshot of the motors and drivers I used.  I drove the
motors at around 30v so they could step faster.

Hope that helps!

Jay

**Comment by xoxota99** [comment]
Thanks, but I don't see the attachment. Maybe github doesn't process attachments in email responses to github issues? If you can reply to me directly at philippe.desrosiers@gmail.com, that would be great!

**Comment by EquipmentAgain** [comment]
Dear Jay.
May you send me any information about the motors you used in your robot?
Model \ Part N \ Manufacture. 
If it will be an attacments, my E-mail Equipa@mail.ru address will be very convinient for this.

**Comment by toughmanshawn** [comment]
Would you please be able to send me the list of parts you used too. Thank you. Email is toughmanshawn@hotmail.com
