### ISSUE TITLE
Motor's data.

### ISSUE THREAD

**Issue by EquipmentAgain** [jayflatland/HighFrequencyTwister#4]
Dear Jay.
May you send me any information about the motors you used in your robot?
Model \ Part N \ Manufacture.
Or just a photo of the motor's label.
You can also use my E-mail: Equipa@mail.ru for your information.

Best Regards,
Sergey.

**Comment by nappiiie** [comment]
Dear Jayflatland, 

I was intrigue by the speed of this robot. I am now trying to build an enhanced version of it. 
Can you also send me the motor used in the video? 
my Email is nopleepp@gmail.com
Thank you in advance 

Sincerely 
NAPPIIE

**Comment by jayflatland** [comment]
Sure!  Motors were 45Ncm Nema 17 Stepper Motor 2A 4-wire.  Motor controllers were StepStick format that fit the RAMPS 1.4 3d printer system.  I used a 36v power supply because steppers need higher voltage to run faster and have good torque.
