### ISSUE TITLE
Help! Can't get OpenCV to recognize colors?

### ISSUE THREAD

**Issue by xoxota99** [jayflatland/HighFrequencyTwister#5]
I Can't for the life of me get OpenCV to recognize the correct colors using the linalg.norm approach that you've got in your code. I've also tried euclidean distance, normalized euclidean, and CIE2000 colorspace (per http://hanzratech.in/2015/01/16/color-difference-between-2-colors-using-python.html ). The tiniest change in lighting makes "Orange" get detected as "White", or "Blue" get detected as "Yellow".

Any tips on how to cut down on the noise in color detection, and get a higher-confidence estimate out of OpenCV?

**Comment by jayflatland** [comment]
That actually was a huge problem for us, something we dealt with by
calibrating immediately before each run.  We didn't come up with any great
robust solution.

**Comment by xoxota99** [comment]
Ah. Glad to know it's not just me, at least :-)

Did you calibrate using a solved/known-state cube?

**Comment by jayflatland** [comment]
Yep, calibrate with solved cube
